# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
